### ISSUE TITLE
Need updated reposado code embedded

### ISSUE THREAD

**Issue by ericholtam** [hjuutilainen/sus-inspector#12]
The latest SUS updates for Catalina started including gzipped dist data that requires an additional flag `--compressed` in reposado to properly read and decompress it. The reposado project has been updated to include that fix, but the SUS Inspector reposado code does not.  Can the project update the reposado code and release a version?

**Comment by ericholtam** [comment]
While we're at it, and before you release a new version, want me to put in a PR to update the default catalogs to include 10.16 on down?

-Eric

**Comment by hjuutilainen** [comment]
Latest reposado is included in 2.0b1
