### ISSUE TITLE
No Window on First Launch - macOS 10.14 Mojave

### ISSUE THREAD

**Issue by alvarnell** [hjuutilainen/sus-inspector#15]
When I launch 2.01b no window opens. I expected to see either the edit window or results of last update. Running fully up-to-date Mojave.

**Comment by hjuutilainen** [comment]
Thanks for reporting.

It seems that the new toolbar search field is causing this on macOS 10.14. The control (NSSearchToolbarItem) was introduced in the latest developer tools and according to WWDC sessions it should be backwards compatible with previous OS versions. Investigating...

**Comment by alvarnell** [comment]
Fixed for macOS 10.14 Mojave in v2.1

**Comment by hjuutilainen** [comment]
Thank you for getting back to this!
