### ISSUE TITLE
No Ventura support

### ISSUE THREAD

**Issue by PhillyPhoto** [hjuutilainen/sus-inspector#26]
I just launched it after not using it for a while and I don't see any Ventura packages. I refreshed the catalog, but it stays with Catalina, Big Sur and Monterey. I'm not sure if this due to a change with how Apple publishes the catalogs?

**Comment by LukeAndrews** [comment]
1. Close SUS Inspector.
2. Run `rm ~/Library/Application\ Support/SUS\ Inspector/SUS_Inspector.storedata` to delete the current config.
3. Open Sus Inspector.
4. The catalog picker window will open. Use the '+' button to add the Ventura catalog at `https://swscan.apple.com/content/catalogs/others/index-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz`
